// build.mjs — scans tools/*.html, reads each <title>, merges meta.json overrides,
// sanitizes placeholder tags, copies pre-rendered thumbnails, and generates a
// static dist/ ready for Vercel. No browser needed here (thumbnails come from
// thumbs.mjs, run separately). Run: node build.mjs   (or: npm run build)

import {
  readFileSync, writeFileSync, readdirSync, mkdirSync, rmSync,
  existsSync, copyFileSync,
} from 'node:fs';
import { join, basename, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = dirname(fileURLToPath(import.meta.url));
const SRC = join(ROOT, 'tools');
const THUMBS = join(ROOT, 'thumbs');
const OUT = join(ROOT, 'dist');
const OUT_TOOLS = join(OUT, 'tools');
const OUT_THUMBS = join(OUT, 'thumbs');

const meta = JSON.parse(readFileSync(join(ROOT, 'meta.json'), 'utf8'));
const site = meta.site || {};
const accent = site.accent || '#0080ff';

// --- reset output ---------------------------------------------------------
rmSync(OUT, { recursive: true, force: true });
mkdirSync(OUT_TOOLS, { recursive: true });
mkdirSync(OUT_THUMBS, { recursive: true });

// --- helpers --------------------------------------------------------------
const TITLE_RE = /<title>([\s\S]*?)<\/title>/i;
const DESC_RE = /<meta[^>]+name=["']description["'][^>]+content=["']([^"']*)["'][^>]*>/i;
// Any <link>/<meta> tag still pointing at the placeholder domain example.com
// (canonical, og:url, og:image, twitter:*, ...) is stripped so no fake URL or
// broken preview image leaks into production.
const PLACEHOLDER_TAG_RE = /[ \t]*<(?:link|meta)\b[^>]*>\s*\n?/gi;

const esc = (s = '') => String(s)
  .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
  .replace(/"/g, '&quot;');

// --- scan tools -----------------------------------------------------------
const files = readdirSync(SRC).filter((f) => f.toLowerCase().endsWith('.html')).sort();
if (files.length === 0) {
  console.error('No .html files found in tools/. Nothing to build.');
  process.exit(1);
}

const records = [];
let sanitized = 0;

for (const file of files) {
  const slug = basename(file, '.html');
  const html = readFileSync(join(SRC, file), 'utf8');

  const rawTitle = (html.match(TITLE_RE)?.[1] || slug).trim();
  const rawDesc = (html.match(DESC_RE)?.[1] || '').trim();

  // Strip any link/meta tag still pointing at the placeholder domain so it does
  // not leak into production SEO or break social previews. Real tags are kept.
  let out = html;
  for (const tag of html.match(PLACEHOLDER_TAG_RE) || []) {
    if (/example\.com/i.test(tag)) {
      out = out.replace(tag, '');
      sanitized += 1;
      console.log(`  · sanitized placeholder tag in ${file}: ${tag.trim().slice(0, 68)}`);
    }
  }
  writeFileSync(join(OUT_TOOLS, file), out);

  // Copy a pre-rendered thumbnail if one exists (generated by thumbs.mjs).
  // Missing thumbnails fall back to a placeholder card, so this stays optional
  // and the Vercel build never needs Playwright.
  const thumbName = `${slug}.jpg`;
  const hasThumb = existsSync(join(THUMBS, thumbName));
  if (hasThumb) copyFileSync(join(THUMBS, thumbName), join(OUT_THUMBS, thumbName));

  const o = (meta.tools && meta.tools[slug]) || {};
  records.push({
    slug,
    href: `tools/${file}`,
    thumb: hasThumb ? `thumbs/${thumbName}` : null,
    name: o.name || rawTitle,
    en: o.en || '',
    subject: o.subject || 'อื่นๆ',
    description: o.description || rawDesc,
    fallbackTitle: rawTitle,
  });

  if (!meta.tools || !meta.tools[slug]) {
    console.log(`  ! no meta.json entry for "${slug}", using <title> "${rawTitle}"`);
  }
}

// --- group by subject -----------------------------------------------------
const order = meta.order || [];
const rank = (s) => (order.indexOf(s) < 0 ? 999 : order.indexOf(s));
const subjects = [...new Set(records.map((r) => r.subject))]
  .sort((a, b) => rank(a) - rank(b) || a.localeCompare(b, 'th'));

const sectionsHtml = subjects.map((subject) => {
  const cards = records
    .filter((r) => r.subject === subject)
    .sort((a, b) => a.name.localeCompare(b.name, 'th'))
    .map((r) => {
      const search = `${r.name} ${r.en} ${r.subject} ${r.fallbackTitle}`;
      const thumb = r.thumb
        ? `<div class="card-thumb"><img src="${esc(r.thumb)}" alt="" loading="lazy" width="1000" height="625"></div>`
        : `<div class="card-thumb is-empty"><span>${esc(r.subject)}</span></div>`;
      return `        <a class="card" href="${esc(r.href)}" target="_blank" rel="noopener"
           data-search="${esc(search).toLowerCase()}" data-subject="${esc(r.subject)}">
          ${thumb}
          <div class="card-body">
            <span class="card-subject">${esc(r.subject)}</span>
            <h3 class="card-name">${esc(r.name)}</h3>
            ${r.en ? `<p class="card-en">${esc(r.en)}</p>` : ''}
            ${r.description ? `<p class="card-desc">${esc(r.description)}</p>` : ''}
            <span class="card-open">เปิดเครื่องมือ &rarr;</span>
          </div>
        </a>`;
    }).join('\n');
  const count = records.filter((r) => r.subject === subject).length;
  return `      <section class="subject" data-subject="${esc(subject)}">
        <h2 class="subject-head"><span class="dot"></span>${esc(subject)}<span class="subject-count">${count}</span></h2>
        <div class="grid">
${cards}
        </div>
      </section>`;
}).join('\n');

const chipsHtml = [`        <button class="chip is-active" data-subject="__all">ทั้งหมด</button>`]
  .concat(subjects.map((s) => `        <button class="chip" data-subject="${esc(s)}">${esc(s)}</button>`))
  .join('\n');

const total = records.length;
const withThumb = records.filter((r) => r.thumb).length;
const stamp = new Date().toLocaleString('th-TH', { dateStyle: 'medium', timeStyle: 'short' });

const favicon = `data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 100 100'%3E%3Crect width='100' height='100' rx='22' fill='%230080ff'/%3E%3Cpath d='M40 30 L72 50 L40 70 Z' fill='white'/%3E%3C/svg%3E`;

// --- page -----------------------------------------------------------------
const page = `<!doctype html>
<html lang="th">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${esc(site.title || 'Interactive Tools')}</title>
<meta name="description" content="${esc(site.tagline || '')}">
<link rel="icon" href="${favicon}">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=IBM+Plex+Sans+Thai:wght@400;500;600;700&family=IBM+Plex+Mono:wght@500&display=swap" rel="stylesheet">
<style>
  :root{
    --accent:${accent};
    --ink:#0f1b2d; --muted:#5a6b82; --line:#e4e9f1;
    --bg:#f6f8fb; --card:#ffffff; --chip:#eef2f8;
  }
  *{box-sizing:border-box}
  html{-webkit-text-size-adjust:100%}
  body{
    margin:0; background:var(--bg); color:var(--ink);
    font-family:"IBM Plex Sans Thai","Segoe UI",Tahoma,sans-serif;
    line-height:1.5; -webkit-font-smoothing:antialiased;
  }
  .wrap{max-width:1080px; margin:0 auto; padding:0 20px}
  .mono{font-family:"IBM Plex Mono",ui-monospace,monospace}

  .masthead{background:var(--card); border-bottom:1px solid var(--line)}
  .masthead .wrap{display:flex; align-items:center; justify-content:space-between;
    gap:16px; padding-top:22px; padding-bottom:22px; flex-wrap:wrap}
  .brand{display:flex; align-items:center; gap:14px}
  .logo{width:42px; height:42px; border-radius:11px; flex:0 0 auto;
    background:var(--accent); position:relative}
  .logo::after{content:""; position:absolute; left:15px; top:11px;
    border-style:solid; border-width:10px 0 10px 16px;
    border-color:transparent transparent transparent #fff}
  h1{font-size:21px; margin:0; letter-spacing:-.01em}
  .tagline{margin:2px 0 0; color:var(--muted); font-size:14px}
  .count-badge{font-size:13px; color:var(--muted); background:var(--chip);
    border:1px solid var(--line); padding:6px 12px; border-radius:999px}
  .count-badge b{color:var(--accent)}

  .controls{display:flex; gap:14px; align-items:center; flex-wrap:wrap;
    padding-top:22px; padding-bottom:6px}
  #search{flex:1 1 260px; min-width:220px; font:inherit; font-size:15px;
    padding:11px 15px; border:1px solid var(--line); border-radius:11px;
    background:var(--card); color:var(--ink)}
  #search:focus{outline:none; border-color:var(--accent);
    box-shadow:0 0 0 3px rgba(0,128,255,.15)}
  .chips{display:flex; gap:8px; flex-wrap:wrap}
  .chip{font:inherit; font-size:13.5px; cursor:pointer; padding:8px 14px;
    border-radius:999px; border:1px solid var(--line); background:var(--card);
    color:var(--muted); transition:.15s}
  .chip:hover{border-color:var(--accent); color:var(--ink)}
  .chip.is-active{background:var(--accent); border-color:var(--accent); color:#fff}

  main{padding:14px 0 60px}
  .subject{margin-top:26px}
  .subject-head{display:flex; align-items:center; gap:10px; font-size:15px;
    margin:0 0 14px; color:var(--muted); font-weight:600}
  .subject-head .dot{width:9px; height:9px; border-radius:50%; background:var(--accent)}
  .subject-count{font-size:12px; background:var(--chip); border:1px solid var(--line);
    color:var(--muted); border-radius:999px; padding:1px 9px}

  .grid{display:grid; gap:14px;
    grid-template-columns:repeat(auto-fill,minmax(248px,1fr))}
  .card{display:flex; flex-direction:column; text-decoration:none; color:inherit;
    background:var(--card); border:1px solid var(--line); border-radius:14px;
    overflow:hidden; transition:.16s; position:relative}
  .card:hover{border-color:var(--accent); transform:translateY(-2px);
    box-shadow:0 8px 22px -12px rgba(0,128,255,.4)}
  .card-thumb{aspect-ratio:16/10; background:var(--chip);
    border-bottom:1px solid var(--line); overflow:hidden}
  .card-thumb img{width:100%; height:100%; object-fit:cover;
    object-position:top center; display:block}
  .card-thumb.is-empty{display:flex; align-items:center; justify-content:center;
    color:var(--muted); font-size:13px; letter-spacing:.03em; text-transform:uppercase}
  .card-body{display:flex; flex-direction:column; flex:1 1 auto; padding:14px 16px 15px}
  .card-subject{font-size:11px; letter-spacing:.04em; color:var(--accent);
    font-weight:600; text-transform:uppercase}
  .card-name{margin:7px 0 2px; font-size:17px; font-weight:600; letter-spacing:-.01em}
  .card-en{margin:0; color:var(--muted); font-size:12.5px}
  .card-desc{margin:9px 0 0; color:var(--muted); font-size:13px; line-height:1.45}
  .card-open{margin-top:auto; padding-top:13px; color:var(--accent);
    font-size:13px; font-weight:600}

  .empty{display:none; color:var(--muted); padding:40px 0; text-align:center}
  .foot{color:var(--muted); font-size:12.5px; padding:24px 0 40px;
    border-top:1px solid var(--line); margin-top:20px}

  @media (prefers-color-scheme:dark){
    :root{--ink:#e8eef7; --muted:#94a6bd; --line:#243244;
      --bg:#0c131d; --card:#141d29; --chip:#1b2735}
    #search:focus{box-shadow:0 0 0 3px rgba(0,128,255,.25)}
  }
</style>
</head>
<body>
  <header class="masthead">
    <div class="wrap">
      <div class="brand">
        <span class="logo" aria-hidden="true"></span>
        <div>
          <h1>${esc(site.title || 'Interactive Tools')}</h1>
          <p class="tagline">${esc(site.tagline || '')}</p>
        </div>
      </div>
      <span class="count-badge"><b id="visible-count">${total}</b> / ${total} เครื่องมือ</span>
    </div>
  </header>

  <div class="wrap controls">
    <input id="search" type="search" placeholder="ค้นหาเครื่องมือ ชื่อ หรือวิชา..." autocomplete="off" aria-label="ค้นหา">
    <div class="chips" id="chips">
${chipsHtml}
    </div>
  </div>

  <main class="wrap">
${sectionsHtml}
    <p class="empty" id="empty">ไม่พบเครื่องมือที่ตรงกับคำค้น</p>
  </main>

  <footer class="wrap foot">
    ${total} เครื่องมือ · อัปเดตอัตโนมัติจากโฟลเดอร์ <span class="mono">tools/</span> · สร้างเมื่อ ${esc(stamp)}
  </footer>

<script>
  var search = document.getElementById('search');
  var chips = document.getElementById('chips');
  var empty = document.getElementById('empty');
  var counter = document.getElementById('visible-count');
  var active = '__all';

  function apply(){
    var q = search.value.trim().toLowerCase();
    var total = 0;
    document.querySelectorAll('section.subject').forEach(function(sec){
      var vis = 0;
      sec.querySelectorAll('.card').forEach(function(card){
        var okQ = !q || card.dataset.search.indexOf(q) !== -1;
        var okS = active === '__all' || card.dataset.subject === active;
        var show = okQ && okS;
        card.style.display = show ? '' : 'none';
        if(show){ vis++; total++; }
      });
      sec.style.display = vis ? '' : 'none';
    });
    counter.textContent = total;
    empty.style.display = total ? 'none' : 'block';
  }

  search.addEventListener('input', apply);
  chips.addEventListener('click', function(e){
    var b = e.target.closest('.chip'); if(!b) return;
    active = b.dataset.subject;
    chips.querySelectorAll('.chip').forEach(function(c){ c.classList.toggle('is-active', c === b); });
    apply();
  });
</script>
</body>
</html>
`;

writeFileSync(join(OUT, 'index.html'), page);

console.log(`\nBuilt dist/ : ${total} tools across ${subjects.length} subjects` +
  (sanitized ? `, ${sanitized} placeholder tag(s) sanitized` : '') + '.');
console.log(`Thumbnails: ${withThumb}/${total} embedded (run "npm run thumbs" to regenerate).`);
console.log('Output: dist/index.html + dist/tools/ + dist/thumbs/');
